### ISSUE TITLE
Stuck in the examples.

### ISSUE THREAD

**Issue by wildeyes** [smallwins/slack#33]
I'm running: 
```
> babel-node index.js

C:\Users\user\Documents\slackbot\node_modules\slack\methods\rtm.client.js:49
        if (callback) callback(err);else throw err;
                                         ^

Error: rtm.start missing params:
- token ... Authentication token (Requires scope: client)

    at Error (native)
    at validate (C:\Users\user\Documents\slackbot\node_modules\slack\methods\_validate.js:31:11)
    at rtmstart (C:\Users\user\Documents\slackbot\node_modules\slack\methods\rtm.start.js:21:36)
    at Object.botListen [as listen] (C:\Users\user\Documents\slackbot\node_modules\slack\methods\rtm.client.js:46:23)
    at Object.<anonymous> (index.js:11:5)
    at Module._compile (module.js:413:34)
    at loader (C:\Users\user\Documents\slackbot\node_modules\babel-register\lib\node.js:158:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\user\Documents\slackbot\node_modules\babel-register\lib\node.js:168:7)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```
.babelrc contains:
```
{"presets": ["es2015"] }
```
index.js contains:
```
import slack from 'slack'

let bot = slack.rtm.client()
let token = process.env.SLACK_TOKEN 

bot.hello(message=> {
  console.log(`Got a message: ${message}`)
  bot.close()
})

bot.listen({token})
```
.env contains: `SLACK_TOKEN=XXXX`

**Comment by brianleroux** [comment]
Hi @wildeyes good news: two very easy solutions. 

Problem is that you need to load the SLACK_TOKEN into the current environment.  

The quickest way is to set the environment variable with the `babel-node` command like so:

```bash
SLACK_TOKEN=xxx babel-node index
```
A slightly easier way is to use a `.env` file but then your code will need to be loading it using something like https://www.npmjs.com/package/node-env-file 

HTH! 💯 

LMK if this works for you so I can close the issue. And don't hesitate to ask followups: I'm happy to help. :shipit:

**Comment by wildeyes** [comment]
Will try it. Thanks a lot. No idea why I assumed an ".env" file I never met
before would get loaded automatically. Perhaps because the example didn't
specify that there more actions needed?

**Comment by brianleroux** [comment]
yea example docs definitely a bad assumption on my part; good first bug if you wanna land some commits here ;)

**Comment by wildeyes** [comment]
Leave this issue open, I’ll pull request when free time allows it :)

**Comment by wildeyes** [comment]
What would you prefer, changing the section "Test setup" to include `node-env-file`, or specifying how to run it with env variables?

**Comment by brianleroux** [comment]
mention both! 🍰

**Comment by brianleroux** [comment]
(If its ok I'm going to close this issue!)
