### ISSUE TITLE
Test case won't transpile

### ISSUE THREAD

**Issue by KamuelaFranco** [smallwins/slack#42]
Having an issue transpiling to run the second usage example. Any help appreciated.
```bash
ERROR in ./~/slack/methods/api.json
Module parse failed: /Users/kamuela/Work/slack-integration/node_modules/slack/methods/api.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:12)
    at Parser.pp$4.raise (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp.semicolon (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:581:61)
    at Parser.pp$1.parseExpressionStatement (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:966:10)
    at Parser.pp$1.parseStatement (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:730:24)
    at Parser.pp$1.parseBlock (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:981:25)
    at Parser.pp$1.parseStatement (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:709:33)
    at Parser.pp$1.parseTopLevel (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:638:25)
    at Parser.parse (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:516:17)
    at Object.parse (/Users/kamuela/Work/slack-integration/node_modules/acorn/dist/acorn.js:3098:39)
 @ ./~/slack/methods/_validate.js 8:11-32
```

**Comment by KamuelaFranco** [comment]
I solved this by removing the exclusion in my webpack config for node_modules transpilation with JSON loader. Any reason why this was needed?

**Comment by brianleroux** [comment]
(sorry for the delay I missed this issue)

not sure -- we publish the transpiled src to npm so no transpile should be needed tho!

**Comment by brianleroux** [comment]
(closing the issue but if you wanna keep digging to see why I'm into it for the science --- can you share teh full webpack config?)
