### ISSUE TITLE
error: Error connecting to <id> Error: fatal_error

### ISSUE THREAD

**Issue by curtisallen** [smallwins/slack#43]
I'm using `slack@7.7.1`, I'm noticing the following stack trace. I'm using the RTM client to receive messages, and web APIs to post messages.

```
[	2016-08-24T14:38:48Z	]	error: Error connecting to 7992c1eda6b0413f9aa2946d2b5d53d7 Error: fatal_error
[	2016-08-24T14:38:48Z	]	at Error (native)
[	2016-08-24T14:38:48Z	]	at Request._callback (/usr/src/app/node_modules/slack/methods/_exec.js:40:16)
[	2016-08-24T14:38:48Z	]	at Request.self.callback (/usr/src/app/node_modules/request/request.js:187:22)
[	2016-08-24T14:38:48Z	]	at emitTwo (events.js:87:13)
[	2016-08-24T14:38:48Z	]	at Request.emit (events.js:172:7)
[	2016-08-24T14:38:48Z	]	at Request.<anonymous> (/usr/src/app/node_modules/request/request.js:1044:10)
[	2016-08-24T14:38:48Z	]	at emitOne (events.js:77:13)
[	2016-08-24T14:38:48Z	]	at Request.emit (events.js:169:7)
[	2016-08-24T14:38:48Z	]	at IncomingMessage.<anonymous> (/usr/src/app/node_modules/request/request.js:965:12)
[	2016-08-24T14:38:48Z	]	at emitNone (events.js:72:20)
[	2016-08-24T14:38:48Z	]	at IncomingMessage.emit (events.js:166:7)
[	2016-08-24T14:38:48Z	]	at endReadableNT (_stream_readable.js:913:12)
[	2016-08-24T14:38:48Z	]	at nextTickCallbackWith2Args (node.js:442:9)
[	2016-08-24T14:38:48Z	]	at process._tickCallback (node.js:356:17)
```

**Comment by brianleroux** [comment]
Hey @curtisallen sorry I am only just noticing this!!! Are you still experiencing the issue?

**Comment by curtisallen** [comment]
No not anymore actually, I only saw this once then it stopped. Thanks for
following up

**Comment by brianleroux** [comment]
😅 😎 no worries my fav kind of bug--thx!
